### ISSUE TITLE
veyor projects failed

### ISSUE THREAD

**Issue by fd00** [sckott/veyor#4]
`veyor projects` failed as follows:
- environment variables `APPVEYOR_ACCOUNT_NAME` and `APPVEYOR_API_TOKEN` not set.
 
```
$ cd /tmp
$ git clone https://github.com/sckott/veyor.git
$ cd veyor
$ bundle install --path=vendor/bundle
$ bundle exec veyor projects
TypeError: no implicit conversion of nil into String
  /tmp/veyor/lib/veyor/request.rb:60:in `+'
  /tmp/veyor/lib/veyor/request.rb:60:in `block in _veyor_get'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:140:in `block in get'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:384:in `block in run_request'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:398:in `block in build_request'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/request.rb:26:in `block in create'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/request.rb:25:in `tap'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/request.rb:25:in `create'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:394:in `build_request'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:379:in `run_request'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:138:in `get'
  /tmp/veyor/lib/veyor/request.rb:56:in `_veyor_get'
  /tmp/veyor/lib/veyor/request.rb:91:in `get'
  /tmp/veyor/lib/veyor.rb:67:in `projects'
  /tmp/veyor/bin/veyor:35:in `projects'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
  /tmp/veyor/bin/veyor:249:in `<top (required)>'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/bin/veyor:23:in `load'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/bin/veyor:23:in `<top (required)>'
```

**Comment by sckott** [comment]
thx for the report @fd00 

this should be fixed now with lastest commit, can you reinstall and try again. It now raises error if token or user name not set
