### ISSUE TITLE
veyor projects failed (set env APPVEYOR_*)

### ISSUE THREAD

**Issue by fd00** [sckott/veyor#5]
`vayor projects` failed as follows:

```
$ cd /tmp
$ git clone https://github.com/sckott/veyor.git
$ cd veyor
$ bundle install --path=vendor/bundle
$ export APPVEYOR_ACCOUNT_NAME=xxxxxxxx
$ export APPVEYOR_API_TOKEN=yyyyyyyy
$ bundle exec veyor projects
TypeError: no implicit conversion of String into Integer
  /tmp/veyor/bin/veyor:38:in `[]'
  /tmp/veyor/bin/veyor:38:in `block in projects'
  /tmp/veyor/bin/veyor:38:in `each'
  /tmp/veyor/bin/veyor:38:in `collect'
  /tmp/veyor/bin/veyor:38:in `projects'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
  /tmp/veyor/bin/veyor:249:in `<top (required)>'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/bin/veyor:23:in `load'
  /tmp/veyor/vendor/bundle/ruby/2.3.0/bin/veyor:23:in `<top (required)>'
```

**Comment by sckott** [comment]
i'm not sure what's going on here. 

what does `Veyor.projects()` give you with the most recent version on master

**Comment by fd00** [comment]
I try with latest.

```
$ cd /tmp
$ git clone https://github.com/sckott/veyor.git
$ cd veyor
$ git describe
v0.1.2-9-gff25bd3
$ bundle install --path=vendor/bundle
$ export APPVEYOR_ACCOUNT_NAME=xxxxxxxx # my account
$ export APPVEYOR_API_TOKEN=yyyyyyyy # my token
$ bundle exec ruby -e 'require "veyor"; p Veyor.projects()'
{"message"=>"Value cannot be null.\r\nParameter name: account"}
```

**Comment by sckott** [comment]
that's weird. the `account` param is not used in `Veyor.projects` . sorry this is taking so long. maybe run trace after to see where that errors coming from

**Comment by fd00** [comment]
It seems that appveyor rest api is wrong now.

```
$ curl -H "Authorization: Bearer ${APPVEYOR_API_TOKEN}" -H "Content-Type: application/json" https://ci.appveyor.com/api/projects                          
{"message":"Value cannot be null.\r\nParameter name: account"}
```

**Comment by sckott** [comment]
that works for me - are you sure your `APPVEYOR_API_TOKEN` is valid?

**Comment by fd00** [comment]
Sorry, I used all accounts v2 API key.
`Veyor.projects()` succeeds using account-specific v1 API key.

**Comment by sckott** [comment]
ah, i didn't know about this different keys. i see now i was using my account specific key. i've opened an issue to see if we can support both #6
